<?xml version="1.0"?>

<!DOCTYPE config [
<!ELEMENT config (option)+>
<!ELEMENT option (introspect?, help, map?, alternative*, custom?)>
<!ATTLIST option
  key CDATA #REQUIRED
  static (true|false) 'true'
  priority NMTOKEN '5'
  type (string|boolean|int-options|string-options|string-array|file|path|directory|number|font|class|custom) #REQUIRED
  class CDATA #IMPLIED
  separator CDATA #IMPLIED
>
<!ELEMENT introspect EMPTY>
<!ATTLIST introspect
  class CDATA #REQUIRED
  property CDATA #REQUIRED
>
<!ELEMENT help (#PCDATA)>

<!ELEMENT map EMPTY>
<!ATTLIST map
  name CDATA #REQUIRED
>
<!ELEMENT custom EMPTY>
<!ATTLIST custom
  class CDATA #REQUIRED
>
<!ELEMENT alternative (#PCDATA)>
<!ATTLIST alternative
  number NMTOKEN #REQUIRED
  name CDATA #REQUIRED
>
]>

<config>
  <option key="Bibles.Default Bible" type="string-options">
  	<introspect class="org.crosswire.jsword.book.Defaults" property="BibleByName"/>
    <help>Which of the available Bibles is the default.</help>
    <map name="biblenames"/>
    <!-- set up in OptionsAction.refreshBooks() along with dict and commentary versions -->
  </option>

  <option key="Bibles.Verses Per Tab" type="number">
  	<introspect class="org.crosswire.jsword.view.swing.book.TabbedDisplayPane" property="PageSize"/>
    <help>How many verses do you want to display on a page before spilling to tabbed mode.</help>
  </option>

  <option key="Sword.Module Search Path" type="path">
  	<introspect class="org.crosswire.jsword.book.sword.SwordBookDriver" property="SwordPath"/>
    <help>Where should we look for SWORD Project modules.</help>
  </option>

  <option key="Sword.Download Directory" type="directory">
  	<introspect class="org.crosswire.jsword.book.sword.SwordBookDriver" property="DownloadDir"/>
    <help>Where should we store newly downloaded modules.</help>
  </option>

  <option key="Remote.Remote Host" type="string-array" separator=" ">
  	<introspect class="org.crosswire.jsword.book.remote.HttpRemoteBookDriver" property="URLs"/>
    <help>The URL of a remote HTTP host.</help>
  </option>

  <option key="Passages.Persistent Naming" type="boolean">
  	<introspect class="org.crosswire.jsword.passage.PassageUtil" property="PersistentNaming"/>
    <help>True if the passage editor re-writes the references to conform to its notation.</help>
  </option>

  <option key="Passages.Blurring Rules" type="int-options">
  	<introspect class="org.crosswire.jsword.passage.PassageUtil" property="BlurRestriction"/>
    <help>What is the default blurring - Blur across chapter boundaries or not.</help>
    <alternative number="0" name="None"/>
    <alternative number="1" name="Book"/>
    <alternative number="2" name="Chapter"/>
  </option>

  <option key="Passages.Book Case" type="int-options">
  	<introspect class="org.crosswire.jsword.passage.BibleInfo" property="Case"/>
    <help>What case should we use to display the references.</help>
    <alternative number="0" name="lower"/>
    <alternative number="1" name="Sentence"/>
    <alternative number="2" name="UPPER"/>
    <alternative number="3" name="mIXeD"/>
  </option>

  <option key="Readings.Readings Set" type="string-options">
  	<introspect class="org.crosswire.jsword.book.readings.ReadingsBookDriver" property="ReadingsSet"/>
    <help>Which of the available readings sets is the default.</help>
    <map name="readings"/>
  </option>

  <option key="Looks.Look and Feel" type="class">
  	<introspect class="org.crosswire.common.swing.LookAndFeelUtil" property="LookAndFeel"/>
    <help>The look and feel of the application</help>
  </option>

  <option key="Looks.Initial Layout" type="int-options">
  	<introspect class="org.crosswire.jsword.view.swing.desktop.Desktop" property="InitialLayoutType"/>
    <help>Do you want to start in SDI, TDI or MDI view mode</help>
    <alternative number="0" name="Tabbed Document Interface"/>
    <alternative number="1" name="Multiple Document Interface"/>
  </option>

  <option key="Looks.Converter" type="string-options">
  	<introspect class="org.crosswire.jsword.util.ConverterFactory" property="CurrentConverterName"/>
    <help>The engine used to genterate the book display</help>
    <map name="converters"/>
  </option>

  <option key="Looks.Simple.Stylesheet" type="string-options">
  	<introspect class="org.crosswire.jsword.view.swing.util.SimpleSwingConverter" property="ResourceName"/>
    <help>The style applied to displayed Books when using the simple styler.</help>
    <map name="swing-styles"/>
  </option>

  <option key="Looks.Configurable.Stylesheet" type="string-options">
  	<introspect class="org.crosswire.jsword.view.swing.util.ConfigurableSwingConverter" property="ResourceName"/>
    <help>The style applied to displayed Books when using the configurable styler.</help>
    <map name="cswing-styles"/>
  </option>

  <option key="Looks.Configurable.Font" type="font">
  	<introspect class="org.crosswire.jsword.view.swing.util.ConfigurableSwingConverter" property="Font"/>
    <help>The font to be used to display books</help>
  </option>

  <!--
  <option key="Looks.Configurable.Font" type="string-options">
  	<introspect class="org.crosswire.jsword.view.swing.util.ConfigurableSwingConverter" property="RealFont"/>
    <help>The font to be used to display books</help>
    <map name="font-names"/>
  </option>
  -->

  <option key="Advanced.Raw.Cache Data" type="boolean">
  	<introspect class="org.crosswire.jsword.book.raw.RawBook" property="DefaultCacheData"/>
    <help>Do new RawBibles cache the entire Bible in memory, or just the indexes.</help>
  </option>

  <option key="Advanced.Reports.Show errors in a dialog box" type="boolean" priority="8">
  	<introspect class="org.crosswire.common.swing.ExceptionPane" property="HelpDeskListener"/>
    <help>Do we display Exceptions in a GUI window.</help>
  </option>

  <option key="Advanced.Reports.Log errors in the log window" type="boolean" priority="8">
  	<introspect class="org.crosswire.common.swing.ExceptionShelf" property="HelpDeskListener"/>
    <help>Do we display Exceptions in a the GUI shelf.</help>
  </option>

  <option key="Advanced.Source Path" type="path" priority="9">
  	<introspect class="org.crosswire.common.swing.ExceptionPane" property="SourcePath"/>
    <help>The directories to search for source code in when investigating an exception.</help>
  </option>

  <option key="Advanced.XSLT.Cache" type="boolean">
  	<introspect class="org.crosswire.common.xml.TransformingSAXEventProvider" property="Cache"/>
    <help>Do we cache the XSLT pages (faster but a pain for development).</help>
  </option>

  <option key="Advanced.Passage.Default Type" type="int-options">
  	<introspect class="org.crosswire.jsword.passage.PassageFactory" property="DefaultPassage"/>
    <help>What type of passage does the PassageFactory create by default.</help>
    <alternative number="0" name="Speed (Rocket)"/>
    <alternative number="1" name="Write Speed (Bitwise)"/>
    <alternative number="2" name="Size (Distinct)"/>
    <alternative number="3" name="Mix (Ranged)"/>
  </option>

  <option key="Advanced.About Dialog.Include Debug Tab" type="boolean">
  	<introspect class="org.crosswire.jsword.view.swing.desktop.AboutPane" property="Debugging"/>
    <help>Is the debug tab visible in the about dialog.</help>
  </option>

</config>
